#실행용 Makefile 만들어서 관리
Link: source/Server/Server source/Client/Client
	ln -s ../source/Server/Server execute/Serv
	ln -s ../source/Client/Client execute/Clie
Serv:
	execute/Serv
Clie:
	execute/Clie
Clean:
	rm execute/Serv
	rm execute/Clie