#Make execute File
execute/Shell: source/CustomShell.c source/FileList.c source/WorkingDirectory.c source/ChangeDirectory.c source/MakeDirectory.c
	gcc -o execute/Shell source/CustomShell.c source/FileList.c source/WorkingDirectory.c source/ChangeDirectory.c source/MakeDirectory.c
Execute:
	execute/Shell
#Delete File 
Clean:
	rm execute/Shell