#Make execute File
execute/Shell: source/CustomShell.c source/FileList.c source/WorkingDirectory.c source/ChangeDirectory.c source/MakeDirectory.c source/ex_rmdir.c source/ex_ln.c source/ex_cp.c source/mv.c source/rm.c source/cat.c
	gcc -o execute/Shell source/CustomShell.c source/FileList.c source/WorkingDirectory.c source/ChangeDirectory.c source/MakeDirectory.c source/ex_rmdir.c source/ex_ln.c source/ex_cp.c source/mv.c source/rm.c source/cat.c
Execute:
	execute/Shell
#Delete File 
Clean:
	rm execute/Shell